name: Release
on:
  pull_request:
    branches:
      - main
    types: [closed]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  tag:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        destribution: temurin
        java-version: 17
    - name: Build and Test
      run: sbt -v +test