name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Scala
      uses: olafurpg/setup-scala@v11
      with:
        java-version: openjdk@1.17
    - name: Cache
      uses: coursier/cache-action@v6
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.github_packages }}
      run: |
        echo ${GITHUB_TOKEN: -3}
        sbt -v "project core" clean publish