name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    environment: Publish
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
      - run: sbtn -v clean
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: sbtn -v publish